# Generated by Django 5.1 on 2024-08-17 13:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('frequency', models.PositiveIntegerField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно'), (30, 'Ежемесячно')], default=7, verbose_name='Периодичность')),
                ('execution_time', models.DurationField(max_length=2, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Время на выполнение')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Только для приятных привычек', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
