# Generated by Django 5.1 on 2024-08-17 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно')], default=7, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность'),
        ),
    ]
