# Generated by Django 5.1 on 2024-08-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='public',
            new_name='is_public',
        ),
    ]
