# Generated by Django 5.0.8 on 2024-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_public_habit_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.DurationField(max_length=2, verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно')], default=1, verbose_name='Периодичность'),
        ),
    ]
